### PR TITLE
Share to google classroom

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #1872

The design is still very much in draft form. I'm using an inline icon for now, just to make editing easier. The geometrical paths in the svg tag are taken from edu.google.com: [Image](https://edu.google.com/images/svg/gsuite-icons/classroom.svg). Use "view source" to see the geometry of the image.

### CODE REVIEW

**Comment by jrochkind** [comment]
Let's leave the icon an SVG if we can, so photoshop wouldn't be the right tool. 

I was imagining simply taking a single-color black google classroom SVG icon I found, and changing it's color to our brand dark grey?  Let's see if I can find that again... Ha, now I can't! But I think it's out there somewhere.

**Comment by eddierubeiz** [comment]
Erin's notes in response to a first draft:

- What do you think of using the yellow and green version of the icon? As a google classroom user, the grey version didn't visually scan "Google Classroom" to me and the logo itself is so tiny I'm not sure I would recognize it without the colors (as compared to the larger logos on the social media buttons, which are much easier to recognize).

- When I click the icon it does take me through the steps to create a post in my classroom, but the object itself is not linked.

**Comment by jrochkind** [comment]
> When I click the icon it does take me through the steps to create a post in my classroom, but the object itself is not linked.

OK, we tried to do the same thing as Erin's DPLA exmaple she gave us: https://dp.la/primary-source-sets/space-race.  So... this is disturbing if it's not working right. 

Can we ask Erin to test DPLA again, and see if it works as she expected, and if our demo is working the same or differnet as the DPLA example?  we tried to copy the DPLA example she gave us, so if it's not working the same as the DPLA example, we didn't succeed, and have to figure out why. But if it is working the same as the DPLA example, but it turns out the DPLA example isn't in fact a good example, it doesn't do what is needed... we'd have to do a lot more work to figure out how to integrate. 

Let's get the integration working in a way we think will satisfy users, before worrying more about how/where it goes on page.

**Comment by eddierubeiz** [comment]
Erin has confirmed the share button is working as it should, by the way.

**Review by jrochkind — APPROVED** [review]

**Comment by eddierubeiz** [comment]
Annabel & Erin agreed on this as good enough to deploy, with the understanding that we can always change the design later if we don't like it:
Final version

**Pull request merged**
