### PR TITLE
Use time (and date) instead of just date for OH request list

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #2429

### CODE REVIEW

**Comment by eddierubeiz** [comment]
See https://staging-digital.sciencehistory.org/admin/oral_history_access_requests

**Comment by eddierubeiz** [comment]
Done.

**Comment by jrochkind** [comment]
@eddierubeiz I see you removed the "OH #" column?  This was intentional, and cleared with OH staff that it's not useful to them, they don't want it? 

Did you remove it because we needed the space? With the line wrap happenign in the date/time anyway... I'm not sure it actually takes up any more horizontal space than it did before? But was it in fact better to remove a column?

Or if they just don't use it or don't need it anyway, I guess might as well remove it when we're looking at this?

**Comment by jrochkind** [comment]
Ah, ok!  Approved!

**Review by jrochkind — APPROVED** [review]

**Pull request merged**
