### PR TITLE
Temporary remove icc profile, so we can ingest grayscale files.

### PR DESCRIPTION
**Pull request by eddierubeiz**
Files newly ingested with this code will need to have their derivatives regenerated once we have a permanent fix.
Ref #942

### CODE REVIEW

**Comment by jrochkind** [comment]
Hmm, I think there was a reason we used the ICC profile though. I am nervous that we are no longer doing it. 

> Files newly ingested with this code will need to have their derivatives regenerated once we have a permanent fix.

Is there an issue or anything to prioritize or remind us to make a "permanent fix"?

Would we have any way at all of identifying which "files were ingested with this code" once we did so?

The fix might be fine permanently; if it is not, however, It doesn't seem to me we are currently in a position to actually reverse it/recover from it.

**Comment by eddierubeiz** [comment]
Good call. Created issue above describing my understanding of the situation.

**Comment by eddierubeiz** [comment]
Note: https://libvips.github.io/libvips/API/current/Using-vipsthumbnail.md.html makes me wonder if we might be able to fix this by using `--eprofile srgb`.

**Comment by jrochkind** [comment]
Issue is #946

**Pull request merged**
