### PR TITLE
Remove `Missing required TIFF ExifIFD .* ColorSpace` ingest check

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #2420

### CODE REVIEW

**Review by jrochkind — APPROVED** [review]

**Comment by eddierubeiz** [comment]
First I removed the validation errors and saved:

```ruby

Work.find_by_friendlier_id('fjcb10k').members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
end
Work.find_by_friendlier_id('ufcf9q1').members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
end
Work.find_by_friendlier_id('s7aeujn').members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
end
Work.find_by_friendlier_id('6d38iie').members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
end
Work.find_by_friendlier_id('3c7748m').members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
end
```

**Comment by eddierubeiz** [comment]
Then I regenerated derivatives:
```bash
heroku run "./bin/rake kithe:create_derivatives -- --work-id=fjcb10k"
heroku run "./bin/rake kithe:create_derivatives -- --work-id=ufcf9q1"
heroku run "./bin/rake kithe:create_derivatives -- --work-id=s7aeujn"
heroku run "./bin/rake kithe:create_derivatives -- --work-id=6d38iie"
heroku run "./bin/rake kithe:create_derivatives -- --work-id=3c7748m"
```

**Comment by eddierubeiz** [comment]
Oh, noticed the fixity checks were missing, then just ran:

```ruby
Work.find_by_friendlier_id('fjcb10k').members.each { |a| a.promote }
Work.find_by_friendlier_id('ufcf9q1').members.each { |a| a.promote }
Work.find_by_friendlier_id('s7aeujn').members.each { |a| a.promote }
Work.find_by_friendlier_id('6d38iie').members.each { |a| a.promote }
Work.find_by_friendlier_id('3c7748m').members.each { |a| a.promote }
```

Now everything looks great.

**Comment by eddierubeiz** [comment]
In retrospect, it's clear the simplest fix would have been:
```ruby
Work.find_by_friendlier_id(friendlier_id).members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
  a.promote
end
```
But eh, no big deal.

**Pull request merged**
