### PR TITLE
ohms features: transcript and index

### PR DESCRIPTION
**Pull request by jrochkind**
Doesn't actually work yet, becuase we don't have combined audio derivative yet, so audio file that is loaded in player and which we seek to for sync links -- won't be right. But can be used to demo with single-audio-file works like duarte. 

Provides an 'oral history' tab in work admin (only for works with genre oral histories) that lets you upload an OHMS XML. (And has some placeholders for where we'll trigger generating a combined audio deriv). 

Then, on oral history audio show page, if OHMS data is present, will show transcript, or index, or both. With sync links. Styling of index is just tentative. 

If no OHMS data is present, audio show pages should be basically unchanged. So, if all is well, we should be able to deploy this now. 

One difference is rights-and-social section swapped to be above download file list, instead of below. Works better for when we have OHMS tabs.

### CODE REVIEW

**Comment by jrochkind** [comment]
At some point in the future when it won't conflict with ongoing work in parallel -- we should rename the "show audio" stuff to "oral_history_with_audio" -- it's really OH specific, and getting more so. And change the condition deciding when to use it to make sure genre == oral histories.

**Comment by jrochkind** [comment]
Hmm, potentially has problems with IE11 on browserstack. 

Bootstrap tabs don't seem to work. Audio player doesn't seem to work. Need to investigate more, and compare to what's already deployed.

**Comment by jrochkind** [comment]
OK, IE11 problem not unique to this branch. 

Audio does not play on master in IE11 either. I don't think the problem is necessarily specific to audio -- I think all JS is broken on IE11. It looks like it might be Blacklight's fault -- perhaps Blacklight does not support IE11 anymore?

**Comment by sanfordd** [comment]
This relates back to #560, not sure if we ever came to a conclusion on our desire to support IE anymore.

**Comment by jrochkind** [comment]
Good call @sanfordd . This branch does seem to work fine on MS Edge.

**Comment by sanfordd** [comment]
Thankfully Edge moving to a Chromium based engine should mean anything that works on Chrome works on Edge.

**Comment by jrochkind** [comment]
This is ready to be _reviewed_ now @eddierubeiz , but  before we _merge_ I wanna check with stakeholders that:

* "index" (ToC) view looks okay -- prefer accordion style? 
* This will change existing audio OH's to have the "Tabbed" UI with Description and Downloads in separate tabs instead of two columns -- is that okay to deploy?

**Comment by eddierubeiz** [comment]
Noted. Will review this evening.

**Comment by jrochkind** [comment]
The OHMS transcript really needed a higher line-height to be legible, so this includes some kind of hacky CSS to allow some areas to have a higher line-height than usual, as well as higher line-height for not only OHMS areas, but work/collection detail page full description areas too. (Stakeholders agreed that was an improvement there too). 

I looked into changing it more places and/or making the longer line-height the default for our serif body font -- but it was turning into more work than I wanted to do right now to make sure the design was still ship-shape changing it in more places.

**Comment by jrochkind** [comment]
This is now ready for review/merge.

**Comment by eddierubeiz** [comment]
No comments. Great work. Merging now!

**Pull request merged**
