### PR TITLE
add tom-select.js filtered multi-select for large-element association select inputs

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #1076 

tom-select JS and CSS added via npm/webpacker, in the "admin" pack that's added only to admin layout.

For the moment, we are NOT doing any AJAX loading here (although tom-select supports it) -- we are still loading all select options in delivered HTML, just using tom-select for a much nicer UI for it.

Used for:

* Work: select collection
* Work/Oral History: select linked interviewer profile
* Work/Oral History: select linked interviewee biography

### CODE REVIEW

**Comment by jrochkind** [comment]
So for what it's worth, for interviewee biography names and interviewer profile names: 

Right now we're loading the whole list of all of them in on the Oral History tab (which actually since it's just a tab is just part of the general Work admin page). 

tom-select would let us move to an AJAX load-on-demand-as-typing-filter, where we don't load the whole list on on page delivery. We're not doing that yet though. 

If we did do that, it looks like it would save 12KB from a currently 125KB page (~10% of page size). So it's definitely a significant amount -- of an already large page, since that multi-tabbed work admin page has a lot on it, all delivered in initial response from server. 

I wonder if I should go ahead and do that now, implement the AJAX load? Not sure. It might be good enough as is.

**Comment by eddierubeiz** [comment]
Noted. It occurs to me that for the average OH work, the"searchable transcript text" also contributes a lot to the size of the HTML.

**Comment by jrochkind** [comment]
Very true, good point. 

That's not a great UI either with regard to HTML DOM size, but it is what was asked for originally -- at that time, I think I still had the unrealistic idea that the oral hsitories with "searchable transcript text" would be the minority edge cases, most would be OHMS-ified. 

Hmm.

**Comment by jrochkind** [comment]
OK, those numbers were wrong too, they were post-gzip numbers -- I got them from Chrome Dev Tools, so they were the difference in *actual* sizes of response, after gzipping that our server does. (We do have a big page). 

Some more careful numbers:

For: https://staging-digital.sciencehistory.org/admin/works/z029p571v

* uncompressed size of "searchable transcript text": 260KB
* uncompressed size of HTML for complete "interviewer profiles" menu: 4KB
* uncompressed size of HTML for complete  "interviewee biographies" menu: 36KB
* total uncompressed size of whole HTML (including full menus) page: 350KB

So I'd say if we care about page size, we should take "searchable transcript text" out. And I think I'll make a GH issue for that. 

interviewer profiles is neglibiel.   interviewee biographies is enough to think about, but agree that don't need to bother with it for now.

**Pull request merged**
