### PR TITLE
Remove the "three month summary" filter on the OH page, and add pagination (intended for merge into `oh_request_dashboard_holding`).

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2511.
Same code as #2508, but intended for merge into the `oh_request_dashboard_holding` holding branch.

### CODE REVIEW

**Comment by jrochkind** [comment]
Thanks, but we still will need to merge master into the holding branch -- I'm not sure I'm visualizing the workflow where this extra PR helps?  Wait, i guess we merge this in.. .then merge master... then when there's conflict say to just take "our branch" version of everything... not sure if it makes it easier in this case. 

If you have a vision of it, do you want to take care of it?  Otherwise, if doing it myself I'll prob just do the merge without this branch!

**Comment by eddierubeiz** [comment]
Yeah, I can take care of it.

**Comment by jrochkind** [comment]
@eddierubeiz Thanks! Taking care of it means merging `master` into `oh_request_dashboard_holding` and then pushing that to git.  Since you'e already merged this, requiring that next step to be done in a way I'm not totally sure how to do, can you do that today before we forget? Thank you!!

**Comment by eddierubeiz** [comment]
Yup, it's taken care of.

**Pull request merged**
