### PR TITLE
Send email from jobs

### PR DESCRIPTION
**Pull request by eddierubeiz**
These settings should allow the Jobs server to send email.
Ref #394

### CODE REVIEW

**Comment by jrochkind** [comment]
Aha, I see the config got a bit complicated with starttls and all, thanks for figuring it out!

Do you think we should wrap the config in a conditional, to only do the new thing when `ScihistDigicoll::Env.lookup(:smtp_host)` is present, otherwise leave the old thing?

i'm not sure what will happen under dev or test if you set the smtp host config to nil. 

Actually, with the code exactly as it is, I know what will happen: `ScihistDigicoll::Env.lookup!(:smtp_host)`, the `!` on the end of `lookup` is the form of the method that will *raise* an exception if no value is present. This is convenient for "fail fast with clear error instead of confusing error down the line" for values we insist on being present -- but in this case, we don't expect it to be present in dev or test, so I think it may end up raising an error in dev or test on boot? (Can you even start the app in dev or run tests locally without an error with this code the way it is?)

So minimally, you should turn that into `lookup` without the `!` -- but maybe also make the new config conditional only if the value is present? Or is that too dangerous cause if it's accidentally not present, emails will just silently fail again?

i'm not totally sure what we should do -- what do we want to happen in dev and test?  Any thoughts?

**Comment by jrochkind** [comment]
> We actually don't want to raise mail delivery errors in production.

I'm not sure if we do or not; maybe we do, to find out about email delivery errors and get a honeybadger notification, instead of having them just silently fail?  Thoughts?

**Comment by eddierubeiz** [comment]
You know what? Let's have them fail loudly if they're misconfigured in prod. I would absolutely want to know right away if e.g. a password reset email wasn't going to get sent.

**Comment by jrochkind** [comment]
okay you’ve changed it to only configure if `ScihistDigicoll::Env.lookup(:smtp_host)` is present — that handles test/dev, where we want the app to be able to start up without local_env :smtp_host defined. (In general, we don't want a local_env.yml to be required in dev/test, the app should start up and run with default configuration for dev/test without it at all). 

But as far as in production… maybe it should raise right away in production? which it now no longer does?

There are two notions of "production" that we could check.  

One is the Rails "environment", which you can check with `Rails.env.production?`. That sets a bunch of Rails configuration defaults for "production mode". We run with it in both staging and true "production", but also very occasionally I run in Rails production environment on dev, when I need to reproduce something only with that config. So if we checked that and raised, then if I was trying to do that on dev, I'd need to set that value (We already have some values like that, which have already been annoying to me :) )

Alternately, we have our own `ScihistDigicoll::Env.lookup(:service_level)` value, which can be `production`, `staging`, or nil. (and ScihistDigicoll::Env [enforces that it must be only one of those three values](https://github.com/sciencehistory/scihist_digicoll/blob/master/app/lib/scihist_digicoll/env.rb#L48)). So we could instead say if it's non-nil, then we'll raise right away if no smtp_host is given.  in dev and test it is nil, it is only production or staging on our deploy environments.

**Pull request merged**
