### PR TITLE
Remove workaround from Rails 7 migration

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #2563

Rails 7 stopped automatically running `yarn install` at app startup, which led to the problem discussed [here](https://github.com/ElMassimo/vite_ruby/discussions/316).
@jrochkind  introduced a [workaround](https://github.com/sciencehistory/scihist_digicoll/commit/6c5672ce53f1dc1c4c4d38496460b55d1dfb5a78) for this problem.

I was [messing around with vite and node](https://github.com/sciencehistory/scihist_digicoll/issues/2498) this week and I believe this workaround is no longer needed, so I'd like to remove it.

With this PR applied, Vite still works fine in dev, and assets still compile on Heroku.

### CODE REVIEW

**Comment by jrochkind** [comment]
Thanks for the archeological spelunking!  You've confirmed you can still deploy to heroku (say staging) on this PR?

**Comment by jrochkind** [comment]
i guess this may expalin that doubling of deprecation messages we were getting from heroku! And getting rid of it may speed up our deploys, avoiding a double install!

**Comment by eddierubeiz** [comment]
Yes, I've deployed this to staging and everything works fine.

**Comment by jrochkind** [comment]
thank you for noticing and fixing this!

**Pull request merged**
