### PR TITLE
Include parents and collections when looking for finding aids

### PR DESCRIPTION
**Pull request by eddierubeiz**
Part of Ref #2627 

See in particular https://github.com/sciencehistory/scihist_digicoll/issues/2627#issuecomment-2274186057 which spells out the metadata guidelines for which works have and don't have finding aid metadata directly attached to them.

### CODE REVIEW

**Comment by jrochkind** [comment]
@eddierubeiz You write 'rather than', but the spec I was anticipating was to look in both places. Does that seem workable?

**Comment by eddierubeiz** [comment]
Missed your comment the other day, but yeah, you're of course right. I'm also looking at parent works (and their collections) in this draft version of the PR.
Once Sarah adds links to the child works mentioned in the [report](https://github.com/user-attachments/files/16366645/Archival.works.in.the.digital.collection.with.no.finding.aid.xlsx), I can amend the PR to ignore parent works before we merge.

**Comment by eddierubeiz** [comment]
Note: I'm replacing a call to method `RelatedLinkFilter#finding_aid_related_links` and replacing it with  a couple lines of inline code. It makes more sense now that we're listing the finding aids for more than one model instance.

**Comment by jrochkind** [comment]
Nice, love how little this took!

**Pull request merged**
