### PR TITLE
Rights terms can include CC licenses, and display reasonably

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #973

CC licenses displayed in "rights" spot need to display somewhat differently. We came up with a wway that seems reasonable. Refactored component to handle them right. Some slight accessibility improvements (alt tag) for existing stuff. 

Some usage guidelines for how to display rightsstatements.org (which we don't totally follow at present): https://rightsstatements.org/en/documentation/usage_guidelines.html

A usage example for how to display CC license can be found eg https://creativecommons.org/choose/results-one?license_code=by-nc-nd&amp;jurisdiction=&amp;version=2.0&amp;lang=en
We use the shorter (cc) logo instead of the complete one, but have full wording so it should be okay. We also use the rel=license markup they recommend for machine-access to license.

### CODE REVIEW

**Comment by jrochkind** [comment]
while this hasn't been reviewed by stakeholders yet (see screenshots at #973), since we aren't yet using this new license term in production data anyway, it can be reviewed and merged into master at any time.

**Comment by jrochkind** [comment]
ready for review/merge

**Comment by eddierubeiz** [comment]
Thanks for dealing with this. Appreciate the removal of the vestigial OralHistoryDeliveryJob, too.

**Comment by jrochkind** [comment]
This PR accidentally ended up including the functionality that was intended to be separated out in  #972 instead. Oh well, now it's merged like this, so be it!

**Pull request merged**
