### PR TITLE
basic ohms validation on existing oral histories

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #754 
`bundle exec rake scihist:check_ohms_xml_data` will run `OralHistoryContent::OhmsXmlValidator.new(model.ohms_xml_text).valid? ` on all oral histories and prints out the results.

### CODE REVIEW

**Comment by jrochkind** [comment]
Looks good. 

We validate on input for new things entered/uploaded, right? This is mainly to check the "historical" stuff that pre-dated that validation?

Do you think we'll ever want to run this again? I wonder if we actually want to merge it, or just use it as I think you already have, and then leave it alone. More code in the codebase is just more code that can eventually stop working or confuse developers trying to find something else etc. Thoughts?

**Comment by jrochkind** [comment]
From the first issue:

> I found two (tiny) footnote errors in staging, and was able to check that they also exist in production. It would be nice to fix them.

This task doesn't like automatically fix anything, right? It just identifies them? So the ones you've already identified, you can go ahead and fix now even before merge, yes? 

I see why we might need to merge to run it in production at all though! What do you think about merging, running in production, then removing from codebase? Alternately, you could just copy and paste the five lines to find invalid into console on production, that's what I've done before for things like this. 

It's good that the existing validation code is well-factored so it's so easy to check em all in 5 lines!

**Comment by eddierubeiz** [comment]
I can't really _fix_ this problem without e.g. adding a footnote to the text or removing a footnote. But we can bring it up on Monday, so people know there are two small problems that need to be addressed.

**Comment by jrochkind** [comment]
I moved to `bundle exec rake scihist:data_fixes:check_ohms_xml_data` so we can keep all temporary data fix rake tasks together. Maybe I'll add a README.

**Pull request merged**
