### PR TITLE
[WIP] Two rake tasks to output shell script that can help us find "broken" external links.

### PR DESCRIPTION
**Pull request by eddierubeiz**
This could be accomplished with faraday, but I'm going with a local script consisting of calls to `curl` instead.
Ref #2220

### CODE REVIEW

**Comment by jrochkind** [comment]
Why calls to curl? 

I would really recommend using ruby.  Not necessarily faraday. The ruby HTTP landscape is a bit disjointed which perhaps makes it seem hard to pick what to use in ruby, but how about maybe http-rb -- which is already in our dependencies, although only indirectly, could be listed in our Gemfile as a top-level dependency too. 

https://github.com/httprb/http

```ruby
response = HTTP.get("https://example.com")
response.status #=> 200

response = HTTP.get("https://www.sciencehistory.org/distillations/video/distilled-5-porcelain-painting")
response.status # => 301
response.headers["Location"] # => "https://sciencehistory.org/distillations/video/distilled-5-porcelain-painting"
```

Okay, that last one is not what I expected... but is the same thing `curl` reports, so that's not the issue. 

(I was expecting a redirect to `/stories` which is what i see happen in the browser... this is a different issue, but if the redirect is really happening in, say, Javascript code or something... oh boy what a pain. If we DO end up needing to actually PARSE html returned, that's even more reason to do this in ruby not do weird things with curl. Separate issue is how we actually identify and detect the bad links that can't be detected with http 404).

**Comment by jrochkind** [comment]
I would like one single rake task that produces a report, not two rake tasks. 

I think there may end up being more than two things we need to check for. 

I am not sure checking for redirect to /stories is actually _right_ (see above), it needs to be tested. 

Part of the task/work is the "analysis" of actually figuring out for sure what to check for.

**Comment by jrochkind** [comment]
AHHH

`https://www.sciencehistory.org/distillations/video/distilled-5-porcelain-painting`

redirects to

`https://sciencehistory.org/distillations/video/distilled-5-porcelain-painting`

which redirects to

`/stories`

Redirects to a relative url!  Seems like it could have also been absolute url. 

I think we're going to need some more complicated logic here, and it's going to be a lot easier with a ruby http client that gives you clear access to parsed response.

**Comment by eddierubeiz** [comment]
I rewrote this without curl in #2273. Closing this PR.

**Pull request closed without merging**
