### PR TITLE
patch Questioning Authority gem to add sort param to OCLC AssignFAST API calls

### PR DESCRIPTION
**Pull request by jrochkind**

### CODE REVIEW

**Comment by jrochkind** [comment]
Want to submit a PR to qa gem itself and link here too.

**Comment by jrochkind** [comment]
failure?? What, ok have to fix that, sorry not actually ready

**Comment by jrochkind** [comment]
Doh failure is just an unreliable test. :(  I think it'll pass on re-run. 

>  1) Oral history with audio display With OHMS synchronized transcript and ToC can display, and search, without errors
     Failure/Error: expect(page).to have_content(%r{Table of Contents — 1 / 7}i)

If so, we gotta either fix that or disable it.

**Review by eddierubeiz — APPROVED** [review]

**Comment by jrochkind** [comment]
Submitted upstream at https://github.com/samvera/questioning_authority/pull/390

**Pull request merged**
