### PR TITLE
Don't download audio files or attempt to create combined derivatives unless we have sensible audio metadata

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2044

This code checks for audio metadata obtained during file characterization (at ingest time). If the metadata doesn't look right, we don't kick off the process of attempting to download the files and stitch them together.

Note that the situation described in #2044 is not a bug per se; the files ingested were not viable audio. So there's really no rush to deploy this.

I also improved the tests.

### CODE REVIEW

**Comment by jrochkind** [comment]
What happens if it decides not to kick off the process?  What does the staff user see, when/where if anywhwere?

Right now, if they click the "create combined audio button" and an unexpected error is raised, they see a "failure" message (after refreshing the page). Is that still true in this case?

Is it logged too?

**Comment by eddierubeiz** [comment]
As of the current (draft) code, it doesn't kick off the `CreateCombinedAudioDerivativesJob.perform_later(@work)` but forwards the user back to the controller with a flash error. It's better in that it's instantaneous, but I'm not sure it's the best we can do.

**Comment by jrochkind** [comment]
Cool, that is pretty good. 

I'm having trouble wrapping my head around the complete process, and if using "metadata missing" as a proxy for "corrupt video" is really even right...   

In the cases we had of corrupt videos, do you know what happens whebn the earlier process tries to extract that format metadata, and fails?  I wonder why we didn't see _that_ error in HoneyBadger in our real world case we had! Or does it just log but not actually raise? Or what?

**Comment by eddierubeiz** [comment]
One thing we have to address before merging this (assuming we want to) is making sure that all audio in the collection is characterized with duration info.

We didn't always have the current setup, so I believe there are files currently in production with nil duration info. If you made a change to those works, then tried to recreate the audio, you wouldn't be able to with this new code.

**Comment by eddierubeiz** [comment]
In response to https://github.com/sciencehistory/scihist_digicoll/pull/2049#issuecomment-1411055532  --
I took a good look at the code and the logged output of `app/uploaders/asset_uploader.rb` -- see:
https://github.com/sciencehistory/scihist_digicoll/blob/ce1dd64d5c1eeb83bec4d8a612aef0826cf017e8/app/uploaders/asset_uploader.rb#L22

Currently `asset_uploader.rb` does not raise or log when
- you ingest a zero-length file with a `flac` file extension or
- you ingest an audio file with gaps in its metadata which render it unplayable.

I do think this is something we could address in a separate PR. I'd put this under ref #1652.

**Comment by jrochkind** [comment]
I'd still love to have some general solution for flagging corrupt files at _ingest_, halting ingest, and notifying/labelling for admins. As per #1652. 

But failing that, or maybe even with that, as an extra layer of defense...  I guess the derivative creator refusing to create derivatives if the files look problematic is good. 

It looks like the CombineAudioDerivativeCreator already had a way of reporting errors in creating the deriv, that was already somehow visible to admin users? This just adds a new category? 

Awesome, thanks!

**Pull request merged**
