### PR TITLE
3 new featured topics

### PR DESCRIPTION
**Pull request by eddierubeiz**
This PR does not include any design work. (which is covered in ref #614).

Ref #600 (portraits of people)
Ref #582 (women in science)
Ref #599 (food science

### CODE REVIEW

**Comment by jrochkind** [comment]
Is it okay to merge this now, it won't mess things up if it's merged and deployed, the new areas will just be ignored until we are ready for them?

**Comment by eddierubeiz** [comment]
Don't merge it yet please; I need one more commit as I neglected to add the subject headings for "Food Science".

**Comment by eddierubeiz** [comment]
Also, careful: the new areas will be visible on the front page as soon as the new `featured_topic.rb` model is deployed. We don't have any feature to turn topics on or off on the front end.

**Comment by jrochkind** [comment]
OK, so we shouldn't merge this until we're sure we're ready for it to be live, and it's been approved by stakeholders, cool. I see the title is still "WIP", cool.

**Comment by eddierubeiz** [comment]
Yup. Fixed the food science list btw.

**Pull request merged**
