### PR TITLE
Removing all import code.

### PR DESCRIPTION
**Pull request by eddierubeiz**
Including:

 - The `import` and `check-against-fedora` rake tasks
 - All importer objects
 - All auditor objects
 - All tests on these objects
 - One or two settings in the codebase.
 - The entire `scripts` directory.

Note: In Ansible, we will also want to remove the `import_fedora_auth` setting from `config/local_env.yml`.

### CODE REVIEW

**Comment by sanfordd** [comment]
@eddierubeiz I'm removing it from staging's branch at the moment.

**Comment by eddierubeiz** [comment]
Thanks!

**Comment by eddierubeiz** [comment]
I am not sure why this is listing e.g. app/assets/stylesheets/local/homepage.scss as having changed from master (it hasn't.) Frustrating.

**Comment by jrochkind** [comment]
> I am not sure why this is listing e.g. app/assets/stylesheets/local/homepage.scss as having changed from master (it hasn't.) Frustrating.

You may have branched off of master before we did merge changes to homepage? But it shouldn't be changing them back. 

Try rebasing or merging master and then pushing again?

Also try changing the 'base' in github PR, then changing it back master, in case it's just GH has gotten confused.

**Comment by eddierubeiz** [comment]
The github base fix didn't work. Will try merging master in dev and then pushing.

**Comment by eddierubeiz** [comment]
Aha!
I merged master earlier today and pushed, but the Travis tests then failed for an unrelated reason. That reason went away. I tried merging master again just now and pushed again, and we now have a) passing Travis tests and b) a correct list of changed files.

**Comment by jrochkind** [comment]
Didn't really review all this, just a whole bunch of removed files. But will merge!

**Pull request merged**
