### PR TITLE
update ruby to 3.1.4

### PR DESCRIPTION
**Pull request by jrochkind**

### CODE REVIEW

**Comment by jrochkind** [comment]
Oops, we actually can't run with 3.1.4 on github actions yet! I don't think this is urgent, we'll try again next week, when it will probably be available. Don't want to merge until we can run our CI with it.

**Comment by jrochkind** [comment]
And oops, 3.1.4 might not be avail on heroku yet. Let's verify it is on staging before merging.

**Comment by jrochkind** [comment]
Nevermind, avail on heroku now too https://devcenter.heroku.com/changelog-items/2561

**Comment by jrochkind** [comment]
taking the liberty of self-review/merge!

**Comment by eddierubeiz** [comment]
Thank you!

**Pull request merged**
