### PR TITLE
Remove extra finding aids

### LINKED ISSUE #2627: add finding aid links to all archives department works without one
### TODO
- [x] Remove now-obsolete finding aids using the rake task at https://github.com/sciencehistory/scihist_digicoll/pull/2726 . The command is `bundle exec rake scihist:data_fixes:remove_extra_finding_aids` .

### Description
Currently, our metadata creation practice is that all works/items belonging to the archives department contain a publicly accessible link from the work in the digital collections to the public finding aid in ArchivesSpace for the collection the work belongs to.

But because we launched the Digital Collections well before the ArchivesSpace public user interface was in use, only archives DC works created _after_ the ASpace PUI was in use contain that link. Approximately 5000 archives works created before the ASpace PUI launch are missing this link and archives staff would like for it to be retroactively added to their metadata. 

Links to finding aids are added to metadata using the Related Link fields:
Category = Finding aid
URL = [something that looks like] https://archives.sciencehistory.org/repositories/3/resources/236

It appears on the front end of the Digital Collections as a visually distinct button ("collection guide") in the Institutional Location section:
institutional location fields DC work

Other info:
All archival collection-level works in the DC _should_ already contain a link to their finding aid in the collection's related link field. Is it possible to have works belonging to these collections automatically inherit this link? As a one-time batch update?

All archival works in the DC _should_ be from a fully processed archival collection that _should_ have a public finding aid in the ArchivesSpace PUI. It is possible, however, that archival items were digitized from collections that do not yet have public records in ArchivesSpace (this shouldn't be happening, but just trying to cover my bases here).

I can generate a CSV containing the accession number (in the DC metadata this is stored in External ID: Accession No.), title, and public URL for each archives collection with a public finding aid and/or only the collections that have digitized content in the DC. 

Also, ASpace has an API and OAI-PMH functionality that are options if we need them for this or other projects.

### PR DESCRIPTION
**Pull request by eddierubeiz**
Last task before we close #2627 .

### CODE REVIEW

**Comment by jrochkind** [comment]
Looks good! This is only going to be used by the data_fixes we probably wont' ever run again?

At first I wondered if we could keep it in data_fixes somehow... but that migth make it hard to test....

Can you at least put a comment at top of file and test saying they are only for use by data_fixes task mention it by name, link to this PR, and say in comment these files can be deleted once data fix task is run?

And add a checkbox to either this PR or the Issue (forget which we do, or both!) for running the data fixes task, with exact copy-and-paste command line to run? 

Thanks!

**Comment by eddierubeiz** [comment]
Added comments - good call.
We'll remove the test, but let's keep the service class and rake task around. I think it's very likely we will end up with more of these stray finding-aid links in the future, so it'll be nice to have this tool to clean them up every couple of years.

**Comment by jrochkind** [comment]
Don't remove the test if you're leaving the code it tests! Ok then.

**Review by jrochkind — APPROVED** [review]

**Comment by eddierubeiz** [comment]
Yeah, I do think we will want to rerun this rake task. Somebody is going to add a duplicate finding-aid link somewhere.

**Comment by eddierubeiz** [comment]
[Results of running this in production](https://github.com/user-attachments/files/16873991/production_results_from_removing_extra_finding_aids.txt)

**Pull request merged**
