### PR TITLE
Work show page

### PR DESCRIPTION
**Pull request by jrochkind**
Goal: Not yet taking account of audio, not yet including viewer or downloads, but basic page layout.

### CODE REVIEW

**Comment by jrochkind** [comment]
Looks like travis works with draft PR's now, as far as running checks? 

I'm not sure why it says "This branch is out-of-date with the base branch". It is not out of date with master as far as I can tell, trying to merge master locally says "Everything up-to-date".

**Comment by jrochkind** [comment]
Haven't totally figured out how to do good tests for a major view like this with lots of functionality. 

Especially when capybara/browser tests are so slow and you don't want to do tons of them. 

This might suggest putting more stuff in easier to test separated ViewModels. 

But I only have so much time for architecture astronauting here. The tests will better than they were in chf_sufia, but probably won't get every detail of display. 

The most important thing is tests that make us confident no 500 will be raised.

**Comment by jrochkind** [comment]
I'm going to call this one ready for review and merge @eddierubeiz . It's big enough already, I'll do any other work in additional PRs. 

Feedback or questions welcome!

**Comment by eddierubeiz** [comment]
OK taking a look...

**Pull request merged**
