### PR TITLE
Add full-work download links to initial work page, indicating presence of searchable pdf

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #2279 

This basically just moves the PDF and (where applicable) ZIP download links to the main work page, no longer hidden behind a menu. 

Additionally, on those on-page links, the PDF is labelled "Searchable" if it will have a text layer from OCR. 

The PDF and Zip links remain in the "downloads" menu for the main "hero" and inside the "image viewer" -- but individual page thumb download menus now only have links for the individual image. 

A fairly simple change, but required some convoluted and confusing code changes because the way we handle rendering of download menus/options winds up being convoluted.  It's currently inflexible, assumed too much about how it would be used that when it changes... is leading to even more convoluted code. 

That whole thing might could use a refactor for present usage patterns at some point.  I think the approach would be really separating the component for _presentation_ from the logic for _what to present_.  The "DownloadOption" model is already a step in this direction.  The `DownloadDropdownComponent` could perhaps do nothing but be _given_ DownloadOptions, it would be other code that would determine _which_ DownloadOptions to use, that could more easily be different in different calling contexts. Instead of trying to pass an ever-growing list of parameters into `DownloadDropdownComponent` that interact in odd permutations to try to instruct `DownloadDropdownComponent` in how to construct the DownloadOptions -- just _give_ it the DownloadOptions constructed externally separating concerns. 

But the nature of the call chains and component trees make it a bit complicated to make work. Would take some thinking through. May not be necessary... it works.

### CODE REVIEW

**Comment by jrochkind** [comment]
Going to re-use the WorkShowOcrComponent for it's logic on identifying whether a work has OCR or not. 

In order to do that safetly, will add unit tests to WorkShowOcrComponent -- it currently has none -- including of specific methods. 

In order to do that, might need some additional Factories for Assets with OCR etc.

**Comment by eddierubeiz** [comment]
Sounds good. Could you double-check there aren't any tests for that component?

**Comment by jrochkind** [comment]
Awesome, I'll check that one out to at least re-use/extract test setup routines though!

**Comment by jrochkind** [comment]
The logic around these on-demand download links is complicated in a bunch of ways. 

I'm doing my best to keep it DRY while keeping the code from getting too convoluted, but it's definitely a bit messy. I'm just proceeding instead of spending too much time working out ideal architectures. 

It involves some calling out to individual methods in ViewComponents to try to to keep DRY, and maybe extracting some such methods.

**Comment by jrochkind** [comment]
Getting there, but we need to

- [ ] keep "whole work" download links OUT of individual thumb download menus 

-- but they should still be in the one on the viewer, AND in the main "hero" image one. The way we have a tree of components here, makes it hard to get the context to know what to do.

**Comment by jrochkind** [comment]
I'm not loving that the SQL to see if all pages _really_ have OCR, on a 422 page book (granted that's big!) adds 45ms to response time. 

What if we just look at `ocr_requested` instead, and show "Searchable PDF" based on that -- even if the OCR is actually missing (maybe it's in queue) so you might not really get text....  should be an unlikely case, hopefully.

**Comment by jrochkind** [comment]
We initially wanted to make the on-page PDF links open in-browser, but in a new tab (instead of forcing download), but complexities involving browser popup blocker made us punt on that for now. See #2389

We originally thought it would be nice to tag PDF as "Searchable" within the `DownloadDropdownComponent` too, but I just kind of got overwhelmed by it, need to do it efficiently.  A redesign really needs to happen as discussed above. It is still flagged in on-page links not hidden behind menu.

**Pull request merged**
