### PR TITLE
Rake task to actually migrate related_url to related_link

### PR DESCRIPTION
**Pull request by jrochkind**
Also adds a new related_link category for distillations_video. 

    rake scihist:data_fixes:convert_related_url

Categories existing related_urls according to their urls, to make them related_links with proper categories. Adds labels for the identified existing related_urls that need em.

Should be idempotent, so we could for instance run in production multiple times if needed, and people are still editing.

### CODE REVIEW

**Review by eddierubeiz — APPROVED** [review]

**Comment by jrochkind** [comment]
Tested in staging, seems to be ok.

**Comment by jrochkind** [comment]
@apinkney0696  CC @eddierubeiz  This migration of data to new `related_links` formats had a few unanticipated aspects -- not sure how we missed them. 

## 1. Some old related works URLs used old legacy app form of URL 

eg https://digital.sciencehistory.org/concern/generic_works/sj1392257

I thought these would get migrated properly, but they didn't. I am currently working on fixing this, right now they show up as weird broken related links, eg https://digital.sciencehistory.org/works/8w32r610x

I will fix this in bulk automatically though. 

## 2. Some related work links had accidental 'admin' links listed

Eg related URL of `https://digital.sciencehistory.org/admin/works/ch4rkz4`, when it should have been `https://digital.sciencehistory.org/works/ch4rkz4`. 

I have found and fixed these manually; but if it's an easy mistake to make, I wonder if we need to automatically catch/prevent it going forward?

If you do this going forward... I think the "related item" link may simply not show up. 

## 3. Related link to a Digital Collection

There were a few Works that had an existing "Related URL" that pointed to a Digital Collection -- but NOT the Collection the Work was listed as being in, a legit "related" one maybe?

This is just a category of existing "Related URL" that we had missed and hadn't reviewed. 

Looks like just three,  two of them were books that were originally found in an archival collection, but were removed to the library ,and are no longer considered part of that collection? So aren't listed as actually being "in" that collection in DC?  

One of them is an Oral History linking to collection of interviewee?

These are still there, I have manually added a "label" so they show up better. You can review and decide what you want to do with them, or with this use case going forward?

See:

* https://digital.sciencehistory.org/works/6ydc1n1
* https://digital.sciencehistory.org/works/evvdhfi
* https://digital.sciencehistory.org/works/k643b2441

**Comment by apinkney0696** [comment]
Thank you for the summary, Jonathan!

2. That would be great if it would automatically remove the "/admin" from the URL, but not a high priority. I used to make that mistake sometimes when I first started working here, but not so much anymore. It would definitely be a nice fail-safe!

3. This is another category we didn't think of initially! Sometimes books are taken from archival collections, so they are related but not actually a part of the collection. And some of our oral history interviewees have donated archives. I think it is important/desirable to make these connections, but the "other internal" category is fine for this use case.

**Comment by jrochkind** [comment]
@apinkney0696 (1) above is now resolved. 

But one more category!

About 15 works included a related_url to this URL: `https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF`

that URL doesn't actually work. The hostname looks like the OPAC. I think that was attempting to link to a PDF Finding Aid via the OPAC, in a manner that the OPAC doesn't actually support for persistent URLs. It's possible the OPAC doesn't support persistent URLs to attachments at all?

Not sure if all of these links should simply be deleted or what. The links are currently still there as `other_internal`. Here is a list of IDs that can be put in URLs to find the works with this link in them.  You can see what happens when a link doens't have a label here too; the URL is used in display. 


```
m0kqkir other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
awyuox5 other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
m9lry8e other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
m0vllje other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
m98gx4e other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
n8ft9di other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
a76z9qh other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
e8l6h8k other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
jz6lcz7 other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
jnz8ypq other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
3vz1mqe other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
qvw1myh other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
d4mxtnm other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
k2zvfnb other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
n2t74my other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
sn9tayj other_internal https://othmerlib.sciencehistory.org/articles/1043273.6965/1.PDF
```

**Comment by apinkney0696** [comment]
Hm, I'm of the opinion that we should delete them all since they all already have a link to the OPAC that will take you to the finding aid link.

**Pull request merged**
