### PR TITLE
use newer kithe with mediainfo-based fallback content-type detection

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #403, should fix, but we need to fix existing uncharacterized files too

### CODE REVIEW

**Comment by jrochkind** [comment]
Once we have characterization working properly, we need to fix existing files. 

We _could_ just force their content-type to `audio/mpeg`, like this:

```ruby
asset.file.metadata["mime_type"] = "audio/mpeg"
asset.save!
```

But better to use the (improved) automated code for detecting mime-type, to ensure we're not setting something that wouldn't have been calculated by the new improved code, and to avoid typos. 

It's a _bit_ cumbersome to do that in shrine 2.x (improved in shrine 3.x which we aren't on yet). 

```ruby
file = asset.file
file.refresh_metadata!
asset.file_data = file.data
asset.save!
```

Or, for the three that are mis-characterized, to re-detect content-type, and then generate derivatives based on newly corrected content-type:

```ruby
["5h73px50k", "bc386k398", "k930bz06p"].each do |friendlier_id|
  asset = Asset.find_by_friendlier_id(friendlier_id)
  file = asset.file
  asset.file_data = file.data
  asset.save!
  asset.create_derivatives
end
```

**Comment by eddierubeiz** [comment]
Noted!

**Comment by jrochkind** [comment]
having trouble getting those items fixed on production, not sure why, will go back to staging to play around with it!

**Comment by jrochkind** [comment]
Ah, had a missing line in my script for fixing the assets -- the all important `file.refresh_metadata!` line. 

Fixed in script above. Run. All assets in https://digital.sciencehistory.org/works/zw12z6384 should be fixed, they are now recognized as audio/mpeg, should have the required derivatives, should be displaying in public UI correctly.

**Pull request merged**
