### PR TITLE
Refactor of work indexer class

### PR DESCRIPTION
**Pull request by eddierubeiz**
This should simplify upcoming changes to the indexer code and make it easier to see what we're doing.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/1317

### CODE REVIEW

**Comment by jrochkind** [comment]
Is a given `field_map[key]` used in more than one place? Can you give an example of where one is used in more than one place? Unless this happens a lot, I'm not totally seeing the advantage of the extra level of indirection with the hash...

Or wait, i see, it's tied into the "feature flag" constants you are using for differnet indexing styles.... So, you didn't htink "feature flags" are overkill here after all, that's basically what these are!   

Why not make it an `ENV` instead, so you can change it without having to make another commit and redeploy code? `ENV['MORE_LIKE_THIS_INDEX_MODE']` which can be `OFF`, `SIMPLE`, `MEDIUM`, or `FANCY`. (not sure these are the right terms, but ok!)

In general, if there is a setting that is mutually exclusive, make it ONE variable that can have four states -- now it can only represent one of four legal states. Instead of four booleans where you need to add an extra check to make sure only one is true, and no illegal state is set. 

In general, I see maybe how this is useful for your testing of four different settings. Although another approach would just be having four (or, really, three) separate branches for each setting. But if you think this is easier ot manage, that's fine. But I'm not in fact sure it makes sense to merge into master for perpeutity... once the testing is done, this seems like additional complexity/indirection that makes the code harder to read and harder to modify (when we add more fields) and is un-needed . That's just my first reaction

**Comment by eddierubeiz** [comment]
Yeah, good reaction! I am not at all opposed to just reverting to a slightly modified version of the original indexer class once we're done with the feature. For the next week this refactor will be really helpful though.

**Comment by jrochkind** [comment]
Well, can you just build your work on this temporary branch without merging it into master? Like do other PR's into this branch if you need to?

**Comment by eddierubeiz** [comment]
Yeah, I can totally do that but I'd rather use an actual feature branch in that case! I can close this and start a feature branch.

**Comment by jrochkind** [comment]
I think I don't understand what makes something an "actual feature branch" or not....

**Comment by eddierubeiz** [comment]
Actually - no need to close this. We can just merge it into `more_like_this_feature` instead of `master`. But yeah, this is now ready for review.

**Pull request merged**
