### PR TITLE
Retrieve previous and next members in a work

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #2322 .

The UI is clunky, but perhaps good enough for a first pass.
I may actually add a second issue for figuring out where to place the links on the page.

Requirements:
- Should work with a combo of assets and works as members
- Doesn't break if there are nil or duplicate positions
- Doesn't break if the positions aren't contiguous integers
- Should be moderately fast
- Should work if the asset or work has no parent

### CODE REVIEW

**Comment by eddierubeiz** [comment]
Featuring my new friends `LAG` and `LEAD`.

**Comment by jrochkind** [comment]
i did not know about lag/lead... I would hae just done two queries `> $current_pos, LIMIT 1`, and `< $current_pos LIMIT 1`. (with ordering ot break ties consistently etc). 

Which I think would have been fine!  But maybe using this fancy thing is fine too? pg-specific? Also fine. As long as there's a test that will fail if it breaks in the future!

**Comment by eddierubeiz** [comment]
(Did a bit of research - turns out `LAG` and `LEAD` are pretty widespread.)

**Comment by jrochkind** [comment]
Very well organized code, with tests, thanks! I like making the helper class, and calling it in the controller. 

Do we really need the _names_ of the previous/next assets on screen? I think not, especially because asset titles aren't very meaningful?

Unless @apinkney0696 has asked for them or wants them, I think simple links  `« PREVIOUS | NEXT »` are best, perhaps greyed-out/not-a-link when you are at first/last?  Similar to our bottom of the page search results pagination. 

Putting extra text on the page can end up just confusing with too many things for the eye to look at, instead of helpful. There is already a lot on this page! 

If you _really_ wanted to, you could make the title a hover popover of some kind, since we do already have it, but I suspect it's not necessary!  As a user, do you want it?

**Comment by eddierubeiz** [comment]
I'll take all these suggestions - thanks!

**Comment by jrochkind** [comment]
And actually, you know what, if we don't need to display the title, taht actually saves you some SQL fetches, does it not? You are doing separate fetches to fetch in the records to get title?

There is probably a way to do that all in one fetch... but if you don't need the titles, and I don't think we do, it's not an issue, don't do those extra fetches!

**Comment by eddierubeiz** [comment]
Good call- stay tuned...

**Comment by jrochkind** [comment]
looking good, thanks

**Pull request merged**
