### PR TITLE
Export Booth papers metadata to a csv file

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #1449

### CODE REVIEW

**Comment by jrochkind** [comment]
Looks fine!

If it wasn't a hacky one-off, I'd say: Why are you fetching the entire Collection to look at what has "Mint" in the subject, instead of just doing a SQL query for only things that have "Mint" in the subject?  

That would be the "right" way to do it. It might be worthwhile as an exersize to do it that way, but it also doesn't really matter for this use-once-then-throwaway with the actual size of our DB. 

I wasn't sure how we were going to get the data from a heroku dyno... but if this works, I guess this works? I'm not totally sure it will, I think the rake exec via heroku is going to insist on putting some prefatory stuff at the beginning of the stdout that will mess up the CSV. Tested on staging yet?  Again, for this simple once-then-done we could just manually edit the output to make it the desired CSV. 🤷

**Comment by eddierubeiz** [comment]
@apinkney0696  -- take a look at this [test run from staging](https://github.com/sciencehistory/scihist_digicoll/files/7621232/booth.csv) when you have a minute.
Thanks!

**Comment by eddierubeiz** [comment]
Yup - six lines at the top of the CSV (4 from Scout) need to be removed.

**Comment by jrochkind** [comment]
I wouldn't think they'd want those XML-like tags `<dc:title>` in there, I can't see how they are going to help them at all in dealing with the CSV, I'd just put the values in in the CSV! But whatever they want!

**Comment by eddierubeiz** [comment]
Re: how I got the list of items, I just wanted to make sure I had the 334 items requested in the issue -- see discussion there for details.

**Review by jrochkind — APPROVED** [review]

**Comment by apinkney0696** [comment]
Hi Eddie, this looks great to me! I agree with Jonathan that the element tags <dc:title>,etc probably shouldn't be included, but that's a pretty easy search and replace that I can do in excel. I also noticed that there are some unicode hex character codes such as "&#x2019;" within some of the descriptions. Is there any way we can make those their typical punctuation symbols? 
Thanks!

**Comment by eddierubeiz** [comment]
Oh, I got rid of the XML tags already - they won't be there when I run this in production.

**Pull request merged**
