### PR TITLE
Make OH keywords no longer look like capsules

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #1953

Not really sure how well this works presently, let's get feedback before merging.

### CODE REVIEW

**Comment by jrochkind** [comment]
@apinkney0696 I'm not really sure how well this works....

-----------
Screen Shot 2022-11-23 at 10 32 49 AM

------------
Screen Shot 2022-11-23 at 10 32 43 AM

------------

I feel like it kinda ends up looking like a wall of text, a scramble of punctuation. 

I'm not totally sure what else to do though, if abandoning the "capsule" style. 

Curious your thoughts. Trying to think of other things that could be done with color or whitespace.... maybe bullets separating the items plus more whitespace?  

I can show you (or others) this live in staging too. Not sure at what point we should ask for OH team feedback.

**Comment by jrochkind** [comment]
OK, I've tried it like this....

--------
Screen Shot 2022-11-23 at 10 57 36 AM

-------
Screen Shot 2022-11-23 at 10 57 21 AM

-------
Screen Shot 2022-11-23 at 10 57 05 AM

--------

I think that's probably better?  Note there can be a line wrap in the middle of a "keyword" phrase... I experimented with preventing that, keeping a "keyword" phrase all on one line, but that ended up causing other oddities in some cases.

**Comment by apinkney0696** [comment]
I love the second option!! Undoubtedly better! I think the wrapping issue is pretty negligible and fine as is. I'll check in with Rachel to make sure she's happy with this and let you know if she has any feedback.

**Comment by rachellane12** [comment]
I agree 100 percent with @apinkney0696. This looks great! The bullet points between the keywords separate them without giving the button look we had before. I also think the wrapping issue isn't a big problem. Really appreciate your work on this, @jrochkind!

**Pull request merged**
