### PR TITLE
customize Faraday middleware on RSolr client to do retries on Solr

### PR DESCRIPTION
**Pull request by jrochkind**
Unclear how safe this Blacklight API is to use, overriding private method in Repository sub-class. But best thing we found to accomplish Solr retries in Blacklight.

Needs:

- [x] Blog this for Blacklight community
- [x] Test this somehow

Ref #1365

### CODE REVIEW

**Comment by jrochkind** [comment]
Current failure is unrelated to us specifically, seems to be a docker-hub outage, which ends up effecting github CI, cause the whole internet is a network of fragile dependencies now. 

https://status.docker.com/

**Comment by jrochkind** [comment]
Blogged it https://bibwild.wordpress.com/2022/01/05/blacklight-automatic-retries-of-failed-solr-requests/

**Comment by eddierubeiz** [comment]
Very cool. Thanks for the tests in particular.

**Comment by jrochkind** [comment]
Thanks, those tests took me like over a day to figure out, but seemed worth it in this case!

**Pull request merged**
