### PR TITLE
add missing header on the OH downloads page

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #2547 
Just adding a title header and a border.

### CODE REVIEW

**Comment by eddierubeiz** [comment]
Screenshot 2024-09-25 at 11 40 11 AM

**Comment by jrochkind** [comment]
I wonder if we want to get rid of all or some of that whitespace before the new first header?

**Comment by eddierubeiz** [comment]
Yeah- this is better:
Screenshot 2024-09-25 at 11 40 11 AM

**Comment by eddierubeiz** [comment]
Yeah - this is better.
Screenshot 2024-09-25 at 1 09 34 PM

**Review by jrochkind — APPROVED** [review]

**Comment by jrochkind** [comment]
I love a screenshot when it's a change to HTML/CSS, but approved regardless!

**Pull request merged**
