### PR TITLE
Copy edit changes to  OH landing page.

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #1185 
- Edits to the collection description are already made in collection metadata in production.
- Nanotechnology blurb follows copy at https://www.sciencehistory.org/oral-history-projects , per Michelle's instructions.
- Making links to the main site open in new tabs.

### CODE REVIEW

**Comment by jrochkind** [comment]
changing title of PR, as it does more than just "Change to the "nanotechnology" blurb on the OH landing page."

**Comment by eddierubeiz** [comment]
Ah yes, thanks.

**Comment by jrochkind** [comment]
@eddierubeiz Wait, of the things asked for in #1185, this does some but not all of them? Is it meant to do all fo them?

I think it's missing the first bullet, should it do that too?

**Comment by eddierubeiz** [comment]
The first bullet is already done. No need to change the code for that, it's just the description of the OH collection.

**Comment by jrochkind** [comment]
Aha! merging, thanks!

(You could put that in the PR description as a record, and to let the reviewer know!)

**Comment by eddierubeiz** [comment]
I did! "Edits to the collection description are already made in collection metadata in production."

**Pull request merged**
