### PR TITLE
Adding a scout config file.

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #1293 
Following instructions on the Scout instructions.
Set log level to `warn`, per current setup.

### CODE REVIEW

**Comment by jrochkind** [comment]
He we already had Scout totally set up and working, without the Scout config file I guess. 

My expectation was that all we'd have to do to do the changeover to new Scout account is change the `SCOUT_KEY` heroku config var per the support instructions:

> Please change your Scout key in Config Var in Heroku to SCOUT_KEY = "" (your new key will become available once your Scout account is created)

No problem playing around with it in staging to see what you can do though!

But I think when I set it up the first time, I guess I got by without the config file, maybe just accepting defaults?  I maybe followed different instructions that didn't tell me to make the config file, I don't know. 

But we do already have Scout totally working -- I think all we need to do is switch to the new Scout account we are setting up, by changing the heroku config var?

**Comment by jrochkind** [comment]
I think we decided not to do this maybe, or not like this?

**Comment by eddierubeiz** [comment]
This file isn't necessary, but if we do merge this, we can remove the `SCOUT_KEY`, `SCOUT_LOG_LEVEL`, `SCOUT_MONITOR` and `SCOUT_NAME` from our production Heroku settings, and store that info in the codebase instead. I do prefer the file to the settings vars, but I don't feel strongly about it.

**Comment by jrochkind** [comment]
As a file, we'd have to make sure it was only enabled in production, or at least had different values in production to keep the staging data separate from the production data (which is recommended by scout docs and also makes sense to me)... so we wouldn't want to merge this as-is... I guess it would have to be ERB (if that file can even be ERB?), that takes values from ScihistDigicoll::Env to have differences in prod and staging?

As it happens, I am currently noticing how every time you run a rake task in staging, the scout gem logs to stdout complaining that Scout isn't configured... I just figured out the solution to this currently when using env to configure, is simply setting config `SCOUT_MONITOR=false` is staging. Which is convenient. 

The config file just seems more complicated to me, with that additional stuff to figure out...

**Comment by eddierubeiz** [comment]
Oh, if we did want this file we would need to add `monitor: false` under `staging`. (Equivalent to the above.)

**Comment by eddierubeiz** [comment]
Closing for now; if we change our mind we can always merge this.

**Pull request closed without merging**
