### PR TITLE
Remove Work#exhibition attribute

### PR DESCRIPTION
**Pull request by jrochkind**
We don't record exhibitions that way anymore, instead we use a feature built on Collection model. Ref #1949, #1920.

Wow there were a lot of places here and there that referenced it! Hope I got em all, tests pass anyway. 

Includes a rake task that must be run to remove all data from this attribute in DB. Rake task operates through #json_attributes only, without referencing exhibition attribute itself, so can be run even after this is merged and exhibition attribute does not exist. 

        ./bin/rake scihist:data_fixes:remove_exhibition_attribute_data

Person who merges should be prepared to deploy and run rake task. 

- [ ] rake task run in production

### CODE REVIEW

**Comment by eddierubeiz** [comment]
There's an extra backup file in here ( `spec/policies/access_policy_spec.rb-NEW` ).
I'm also curious what `spec/args_template.rb` is doing; you don't appear to be using the `allow [...] to receive` recipe anywhere in the tests of this PR. Am I missing something?

**Comment by jrochkind** [comment]
Gah, thank you Eddie, good catches!

There were so many changed files that I ended up accidentally committing some leftover temp files that weren't even from this specific work! They were just leftover temp working files. Will try to clean up!

**Comment by jrochkind** [comment]
OK, removed those two files, I think they were the only ones that snuck in! Thank you for your review!

**Comment by eddierubeiz** [comment]
No worries. I think it's just `Procfile.dev` - other than that it looks great and I approve it!

**Comment by jrochkind** [comment]
Thank you for catching that again, I will remove Procfile.dev! Hooray for code review!

**Comment by jrochkind** [comment]
Rake task to rehabilitate the data was having some problems on prod... may run more manually....

**Comment by jrochkind** [comment]
resolved

**Pull request merged**
