### PR TITLE
required fields to publish a record

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #372

### CODE REVIEW

**Comment by jrochkind** [comment]
So our default `work` factory for tests created a "published" work, but didn't include the now required fields for published works. So a bunch of tests failed on validation errors. 

I can:

A) Change the default `:work` factory to include the required-for-publication fields. 

B) Change the default `:work` factory to be a non-published work, add a `:published` trait for a published work, and change any existing tests that just do `create(:work)` to instead do `create(:work, :published)` if they need a published work. I'd find out which tests these are by simply changing the default work factory to be non-published, and looking at test failures. 

@eddierubeiz Any sense of whether A or B would be preferable? I'm not really sure.

**Comment by eddierubeiz** [comment]
Hm. I would argue B is preferable. It's a little more work but we won't regret having that choice in the future. And I think the factory should yield unpublished works by default.

**Comment by jrochkind** [comment]
OK, I guess we can merge and deploy this one now. 

But there's no rush, and it's some kinda weird code, so do please take a look at the code in a non-hurried fashion. :)

**Comment by eddierubeiz** [comment]
Let's plan on merging / deploying this afternoon.

**Pull request merged**
