### PR TITLE
ActiveJob retry_on to retry ALL failed jobs once, still with resque

### PR DESCRIPTION
**Pull request by jrochkind**
Ref #607 

* retry once for StandardError (basically any error) in ApplicationJob super-class of all our jobs. The intent is that any failure should be re-enqueued for a retry ONCE, immediately, before giving up. This should resolve intermittent errors or errors caused by the Job dyno being shut down mid-job.

* Basic resque isn't able to schedule future jobs. Patch the resque adapter so it IS willing to `retry_on` with `wait:0`, just by doing an ordinary job enqueue.

* Retry logging is not great. Customize the ActiveJob retry logging by making a custom rails log subscriber for ActiveJob (based on the default one, by subclass), and using our custom one in place of the default one.

### CODE REVIEW

**Comment by jrochkind** [comment]
Custom logging is in part set up so we can set up papertrail alerts, for instance `[ActiveJob] AND retrying` to have papertrail let us know when/how often retries are happening, with, once you jump into the logs, the necessary context to see what was going on. 

The default logging made it hard to target just these messages ("ActiveJob" didn't appear in the line), and also made it hard to then see it in context -- the job_id didn't appear in the line, with the job_id you can click on it in papertrail to see all the other lines from that job_id.

**Comment by jrochkind** [comment]
Re logging... there is this gem, but I'm not sure how maintained/currently working it is, or if it just handles exception logging.  We could try to update/write it or an alternative ourselves....

https://github.com/armandmgt/lograge_active_job

**Comment by jrochkind** [comment]
Blog post with things discovered and choices made: https://bibwild.wordpress.com/2021/08/23/notes-on-retrying-all-jobs-with-activejob-retry_on/

**Comment by jrochkind** [comment]
I created a Papertrail saved search and alert on `[ActiveJob] AND Retrying`. https://papertrailapp.com/searches/123664271/edit`

It alerts to Slack errors channel (I think?), and email digital-tech@sciencehistory.org. 

This way we can have some sense of how often retries are happening!  The custom logging was in part to make sure we had clear unique things to filter on for this alert, as well as enough info in the log messages so filtered to have a sense of what was going on and be able to find out details!

**Comment by eddierubeiz** [comment]
Thanks for the extra-helpful narrative in the blog post -- makes it a lot easier to see what's going on here. Looks like this was fun to work on!

**Pull request merged**
